spring.application.name=springmvcpractice
spring.datasource.name=JDBCDEMO
spring.datasource.url=jdbc:mysql://localhost:3306/JDBCDEMO
spring.datasource.username=root
spring.datasource.password=123.com
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update